# Generated by Erlang.mk. Edit at your own risk!

ERTS_INCLUDE_DIR ?= /usr/lib/erlang/erts-11.1.8/include/
ERL_INTERFACE_INCLUDE_DIR ?= /usr/lib/erlang/lib/erl_interface-4.0.2/include
ERL_INTERFACE_LIB_DIR ?= /usr/lib/erlang/lib/erl_interface-4.0.2/lib
ERTS_DIR ?= /usr/lib/erlang/lib/erts-11.1.8
