-define(ERROR(Fmt), lager:error(Fmt)).
-define(ERROR(Fmt, Args), lager:error(Fmt, Args)).
-define(INFO(Fmt, Args), lager:info(Fmt, Args)).
-define(INFO(Fmt), lager:info(Fmt)).
-define(WARN(Fmt, Args), lager:warn(Fmt, Args)).
-define(WARN(Fmt), lager:warn(Fmt)).
